services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: govn
      POSTGRES_USER: root
      POSTGRES_PASSWORD: quan@123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

volumes:
  pgdata: